import createClient from 'openapi-fetch'

// schema.d.ts is generated by `pnpm gen:api` (openapi-typescript) from the
// running FastAPI dev server's /openapi.json. Until the first generation, the
// import will be unresolved — that's fine; the client still works at runtime.
import type { paths } from './schema.ts'

export const api = createClient<paths>({
  baseUrl: '/api/v1',
  credentials: 'include',
})
